import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderBar from "./components/header-nav-bar";
import NavContext from "./components/navigation-context";
import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en" style={{ scrollbarGutter: "stable" }}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <NavContext>
            {children}
            {/* <div style={{ viewTransitionName: "nav-button" }}> */}
            {/* </div> */}
          </NavContext>
        </body>
      </html>
    </ViewTransitions>
  );
}
