import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderBar from "./components/header-nav-bar";
import NavContext from "./components/navigation-context";
import ScrollRestorationDisabler from "./components/scroll-restoration-disabler";
import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // title: "Create Next App",
  title: "Tierra Verde Office Web Utilities",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        // style={{ scrollbarGutter: "stable", scrollBehavior: "smooth" }}
      >
        <ScrollRestorationDisabler />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          {true && (
            <div>
              Nevermind, management told me I was stepping on their toes and the
              idea was not just unhelpful, useless, unappreciated, but actually
              offensive. If the idea of this tool is something you would like
              expaned upon, please remind yourself that providing free help with
              no expectation is a BAD THING and should be DISCOURAGED. If you're
              curious about the floor shedule, take a picture of the physical
              document like usual.
            </div>
          )}
          {false && (
            <div>
              <NavContext>
                {children}
                {/* <div style={{ viewTransitionName: "nav-button" }}> */}
                {/* </div> */}
              </NavContext>
            </div>
          )}
        </body>
      </html>
    </ViewTransitions>
  );
}
